version = 1

[unsloth/medgemma-27b-it-GGUF:Q8_K_XL]
; du 31GB
; nvtop: 43.4 GB
; PP: 2900 t/s
; TG:   24 t/s
ctx-size=131072
fit=off
gpu-layers=all


[bartowski/orcarouter_Qwen3.8-27B-Uncensored-GGUF:Q8_0]
; PP: 2300 t/s
; TG:   77 t/s
; du    21GB
; nvtop 41GB
ctx-size=201000
temp=1.0
top-p=0.95
top-k=20
min-p=0.00
repeat-penalty=1.0
fit=off
gpu-layers=all
gpu-layers-draft=all
kv-unified=1
spec-type=draft-mtp


[unsloth/Qwen3.8-Flash-Next-GGUF:Q4_K_XL]
; du 106GB
; nvtop 47GB VRAM + 52GB+ RAM
; PP:  580 t/s
; TG:   32 t/s
ctx-size=200000
batch-size=4096
ubatch-size=40963
temp=1.0
top-p=0.95
top-k=20
min-p=0.00
repeat-penalty=1.0
threads=10
