version = 1
; sudo du -h -d 1  /var/lib/docker/.cache/huggingface/hub

[unsloth/medgemma-27b-it-GGUF:Q8_K_XL]
; du 31GB
; nvtop: 43.4 GB
; PP: 2900 t/s
; TG:   24 t/s
ctx-size=131072
fit=off
gpu-layers=all


[BoldingBuilds/orcarouter_GLM-5.3-Flash-Uncensored-GGUF:IQ3_XXS]
; du 127GB
; PP 600 t/s
; TG  15 t/s
; nvtop: 96GB VRAM + 50GB RAM
ctx-size=65536
threads=10
batch-size=4096
ubatch-size=4096
;disable vision +1 t/s TG
;no-mmproj=1      


[unsloth/Qwen3.8-Flash-Next-GGUF:Q4_K_XL]
; du 106GB
; nvtop 96GB VRAM + 6GB RAM
; PP: 2100 t/s
; TG:   63 t/s
ctx-size=200000
batch-size=4096
ubatch-size=40963
temp=1.0
top-p=0.95
top-k=20
min-p=0.00
repeat-penalty=1.0
threads=10
